"""
ⒸAngelaMos | 2025
constants.py
"""

EMAIL_MAX_LENGTH = 320
PASSWORD_MIN_LENGTH = 8
PASSWORD_MAX_LENGTH = 128
PASSWORD_HASH_MAX_LENGTH = 1024
FULL_NAME_MAX_LENGTH = 255

TOKEN_HASH_LENGTH = 64
DEVICE_ID_MAX_LENGTH = 255
DEVICE_NAME_MAX_LENGTH = 100
IP_ADDRESS_MAX_LENGTH = 45

PRODUCT_NAME_MAX_LENGTH = 255
PRODUCT_SLUG_MAX_LENGTH = 255
PRODUCT_TAGLINE_MAX_LENGTH = 500
PRODUCT_DESCRIPTION_MAX_LENGTH = 10000
PRODUCT_URL_MAX_LENGTH = 2048
PRODUCT_INSTALL_COMMAND_MAX_LENGTH = 1000
PRODUCT_CATEGORY_MAX_LENGTH = 50
PRODUCT_STATUS_MAX_LENGTH = 50

FEATURE_TITLE_MAX_LENGTH = 255
FEATURE_DESCRIPTION_MAX_LENGTH = 2000
FEATURE_ICON_MAX_LENGTH = 100

MEDIA_URL_MAX_LENGTH = 2048
MEDIA_TYPE_MAX_LENGTH = 50
MEDIA_ALT_TEXT_MAX_LENGTH = 500
MEDIA_CAPTION_MAX_LENGTH = 1000

API_VERSION = "v1"
API_PREFIX = f"/{API_VERSION}"
